### PR TITLE
#31: bugfix AlreadyDisposedException

### LINKED ISSUE #31: AlreadyDisposedException: Already disposed: Module: '<module-name>'
### Stack trace:

```
com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Module: '<module-name>'
	at com.intellij.serviceContainer.ComponentManagerImpl.checkStateAndGetPicoContainer(ComponentManagerImpl.kt:132)
	at com.intellij.serviceContainer.ComponentManagerImpl.getComponent(ComponentManagerImpl.kt:350)
	at com.intellij.openapi.roots.ModuleRootManager.getInstance(ModuleRootManager.java:37)
	at saigonwithlove.ivy.intellij.shared.Modules.getContentRoot(Modules.java:108)
	at saigonwithlove.ivy.intellij.shared.Modules.getPomFile(Modules.java:103)
	at saigonwithlove.ivy.intellij.shared.IvyModule.isPomModified(IvyModule.java:64)
	at saigonwithlove.ivy.intellij.shared.IvyModule.getMavenModel(IvyModule.java:45)
	at saigonwithlove.ivy.intellij.shared.Modules.lambda$resolveDependency$4(Modules.java:83)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.noneMatch(ReferencePipeline.java:538)
	at saigonwithlove.ivy.intellij.shared.Modules.lambda$null$2(Modules.java:71)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at saigonwithlove.ivy.intellij.shared.Modules.lambda$getMissingIvyDependencies$3(Modules.java:72)
	at java.base/java.util.Optional.map(Optional.java:265)
	at saigonwithlove.ivy.intellij.shared.Modules.getMissingIvyDependencies(Modules.java:75)
	at saigonwithlove.ivy.intellij.toolwindow.module.ModuleCellRenderer.customizeCellRenderer(ModuleCellRenderer.java:38)
	at saigonwithlove.ivy.intellij.toolwindow.module.ModuleCellRenderer.customizeCellRenderer(ModuleCellRenderer.java:19)
	at com.intellij.ui.ColoredListCellRenderer.getListCellRendererComponent(ColoredListCellRenderer.java:47)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at java.desktop/javax.swing.JList.getToolTipText(JList.java:1543)
	at com.intellij.ide.IdeTooltipManager.isTooltipDefined(IdeTooltipManager.java:244)
	at com.intellij.ide.IdeTooltipManager.eventDispatched(IdeTooltipManager.java:151)
	at java.desktop/java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2199)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2091)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2090)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2090)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2090)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2090)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2090)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2090)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2090)
	at java.desktop/java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2047)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4932)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4560)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Reason

User removed module, but Ivy Plugin is still using it.

### PR DESCRIPTION
**Pull request by zadewu**
fix #31 
Handle the exception AlreadyDisposedException by register a listener to IntelliJ module listener. When a module is closed, then the listener will remove the module from preference state and update it to prevent error from CellRender

### CODE REVIEW

File: src/main/java/saigonwithlove/ivy/intellij/settings/IvyModuleListener.java [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+    PreferenceService preferenceService = project.getService(PreferenceService.class);
+    List<IvyModule> initialModulesCopy =
+        new ArrayList<>(preferenceService.getState().getIvyModules());
+    List<IvyModule> remainingModules =
+        initialModulesCopy.stream()
+            .filter(item -> !item.getName().equalsIgnoreCase(module.getName()))
+            .collect(Collectors.toList());
+    preferenceService.update(
+        (oldState -> {
+          State newState = new State();
```
Comment (cavoirom) [inline src/main/java/saigonwithlove/ivy/intellij/settings/IvyModuleListener.java]: Hi @zadewu, no need to create new state. you only need to `setIvyModules`. I checked the implementation, it will not differentiate the state.

For example:

```
        preferenceService.update(
            state -> {
              configuration.setValue(newValue);
              state.getServerProperties().put(configuration.getName(), configuration);
              return state;
            });
```

Comment (zadewu) [reply src/main/java/saigonwithlove/ivy/intellij/settings/IvyModuleListener.java]: Hi @cavoirom, I adjust the code and also do the test. It can run normally

**Comment by zadewu** [comment]
Hi @cavoirom , I also think beside of fixing this bug, we can use this class and listen to the addModule event. We can refresh the modules for CellRender again without the need to restart IDE as before. I adjust the code, please help me to review the idea as well. Thank you

**Review by cavoirom — APPROVED** [review]
Look good to me. It's nice that you addressed the adding module case. Thank you very much.
