### PR TITLE
Fix bug OSGI directory not found

### LINKED ISSUE #5: OSGI directory not found
Current situation:
- Ivy Engine is missing some library folders if we don't start it at least one time.

Expected behavior:
-Ivy Plugin should automatically know about this situation and start Ivy Engine to generate needed folders, then stop Ivy Engine and create libraries as usual.

### PR DESCRIPTION
**Pull request by zadewu**
This fix doesn't include stop engine when it already started. I don't know how to stop it yet.

### CODE REVIEW

**Comment by cavoirom** [comment]
After take an overview on the PR, as I understood, the main goal of the PR is **detect the OSGI folder exists or not**, this is the sign for us to take next action:

1. It's mandatory to have OSGI folder to create the libraries in IntelliJ.
2. The fresh installed Ivy Engine doesn't have this folder.
3. When we start Ivy Engine for the first time, it create the OSGI folder.

Our solution is checking the OSGI folder and start the Ivy Engine if needed.

I have some suggestion for the PR:

- We should do the "check OSGI folder" in InitializationActivity.updateLibraries
- We can move the isOsgiFolderExist to IvyEngineService, all Engine related behaviors will go to this class.
- When the OSGI folder NOT exist, I suggest display the dialog inform user start Ivy Engine one time by clicking on Play button in Ivy Plugin panel, then restart the IntelliJ, we will skip updating Libraries when OSGI not exist. This solution is not convenience but it's simple, because I see the code to run Ivy Engine automatically much complicated and not stable (require another thread to frequently check the log file, which is not the direct way to check the state of Ivy Engine). The most direct way to do is extract the osgi bundle to correct folder, we may find the way to do it later.
- The ivy-intellij plugin use google-java-format code style, you should use google-java-format plugin in your IntelliJ and format all Java file follow this style.

File: src/main/java/saigonwithlove/ivy/intellij/shared/LibrarySyncInvoker.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+import com.intellij.openapi.ui.MessageDialogBuilder;
+import com.intellij.openapi.ui.Messages;
+import lombok.NoArgsConstructor;
+import org.apache.commons.lang3.StringUtils;
+import org.jetbrains.annotations.NotNull;
+import saigonwithlove.ivy.intellij.engine.IvyEngineService;
+import saigonwithlove.ivy.intellij.settings.PreferenceService;
+
+@NoArgsConstructor
+public class LibrarySyncInvoker {
```
Comment (cavoirom) [inline src/main/java/saigonwithlove/ivy/intellij/shared/LibrarySyncInvoker.java:17]: I'm sorry for writing many comments. I just want to make the code as consistent as possible, please forgive me about this.

When writing GUI application like this one, we will try to separate GUI code with back-end code. In this case, the GUI code will inside IvySettingView and InitializationActivity, the back-end code will go to IvyEngineService. We will try not to introduce new term. The LibrarySyncInvoker may not needed because its code can split into the above classes.

I can imagine the code will look like this in IvySettingView and InitializationActivity
```
PreferenceService.State preferences = preferenceService.getState();
IvyEngineService ivyEngineService = ServiceManager.getService(project, IvyEngineService.class);
if (ivyEngineService.isOsgiFolderExist(preferences.getIvyEngineDirectory()) {
  ApplicationManager.getApplication().runWriteAction(() -> ServiceManager.getService(project, IvyEngineService.class).addLibraries(preferences.getIvyEngineDirectory()));
} else {
  int result = MessageDialogBuilder.yesNo(..).yesText("Start Engine").noText("Manually start").project(project).show();
  if (result == Messages.YES) {
    ivyEngineService.startIvyEngine(preferences.getIvyEngineDirectory(), project);
  }
}
```

This code is still duplicated but more readable, we don't need to go to another layer to see what the code does.

Notice the messages, those "text" messages will be put in `resources.messages.IvyBundle.properties`, we can do i18n easier.

Git cheat:
- Please use the issue id when you do a commit, in this case, you fix the issue #5
- For the nicer git history, you can do `git squash` or `git commit --amend` and then force push to your branch, by doing this, we can eliminate commit with tiny change.

**Comment by cavoirom** [comment]
This PR is related to issue #5

File: src/main/java/saigonwithlove/ivy/intellij/shared/LibrarySyncInvoker.java (hunk 1 above)
Comment (zadewu) [reply src/main/java/saigonwithlove/ivy/intellij/shared/LibrarySyncInvoker.java:17]: It's fine. I want to learn more, so please don't hesitate to comment. For this point I get your idea but I have one concern. What if user select Setting > choose another directory. Should we also show the warning dialog? If we do then we do same thing with the behaviour at InitializationActivity. Then how can we centralize in this case?

Comment (cavoirom) [reply src/main/java/saigonwithlove/ivy/intellij/shared/LibrarySyncInvoker.java:17]: Yes, we have to duplicate the block of code above, it should be the same in `IvySettingView` and `InitializationActivity`. The `IvySettingView` handles setting change you mentioned, the `InitializationActivity` will update libraries automatically at startup. I can't find the way to centralize this block that satisfy me, we can accept the code duplication in this case.
